title: Grow Pixel
email: ryan@growpixel.com
description: >- # this means to ignore newlines until "baseurl:"
  A games and experience design company best known for Blackbox,
  a collection of puzzles for iOS where you don't touch the screen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.growpixel.com" # the base hostname & protocol for your site
lang: en_US

twitter: 
  username: blackboxpuzzles
  card: summary

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key will not be processed.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
